/**
 * Generate and download a PDF from formatted lesson text (markdown-ish).
 * Uses jsPDF for vector text output.
 */
export async function exportLessonPDF(formattedText, filename = 'lesson-plan.pdf') {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'letter' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginL = 20;
  const marginR = 20;
  const marginT = 20;
  const marginB = 25;
  const maxW = pageWidth - marginL - marginR;

  let y = marginT;

  function checkPage(needed = 8) {
    if (y + needed > pageHeight - marginB) {
      doc.addPage();
      y = marginT;
    }
  }

  function addText(text, opts = {}) {
    const {
      fontSize = 10,
      fontStyle = 'normal',
      color = [40, 40, 40],
      indent = 0,
      lineGap = 2,
    } = opts;

    doc.setFontSize(fontSize);
    doc.setFont('helvetica', fontStyle);
    doc.setTextColor(...color);

    const lines = doc.splitTextToSize(text, maxW - indent);
    for (const line of lines) {
      checkPage();
      doc.text(line, marginL + indent, y);
      y += fontSize * 0.352778 + lineGap; // pt to mm
    }
    y += 1; // small gap after block
  }

  function addHRule() {
    checkPage(4);
    doc.setDrawColor(200, 200, 200);
    doc.line(marginL, y, pageWidth - marginR, y);
    y += 4;
  }

  // Parse and render the formatted text
  const lines = formattedText.split('\n');

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (line.startsWith('# ')) {
      checkPage(14);
      y += 3;
      addText(line.slice(2), { fontSize: 18, fontStyle: 'bold', color: [30, 64, 175] });
      addHRule();
    } else if (line.startsWith('## ')) {
      checkPage(10);
      y += 4;
      addText(line.slice(3), { fontSize: 13, fontStyle: 'bold', color: [30, 64, 175] });
      y += 1;
    } else if (line.startsWith('### ')) {
      checkPage(8);
      y += 2;
      addText(line.slice(4), { fontSize: 11, fontStyle: 'bold', color: [55, 65, 81] });
    } else if (line.startsWith('- **') || line.startsWith('* **')) {
      // Bold list item like "- **Teacher:** John"
      const content = line.replace(/^[-*]\s*/, '');
      const boldMatch = content.match(/^\*\*(.+?)\*\*:?\s*(.*)/);
      if (boldMatch) {
        checkPage(6);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(40, 40, 40);
        const labelW = doc.getTextWidth(boldMatch[1] + ': ');
        doc.text(boldMatch[1] + ':', marginL + 4, y);
        doc.setFont('helvetica', 'normal');
        const rest = doc.splitTextToSize(boldMatch[2], maxW - 4 - labelW);
        doc.text(rest[0] || '', marginL + 4 + labelW, y);
        y += 6;
        for (let i = 1; i < rest.length; i++) {
          checkPage();
          doc.text(rest[i], marginL + 4 + labelW, y);
          y += 5.5;
        }
      } else {
        addText('• ' + content, { indent: 4 });
      }
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      addText('• ' + line.slice(2), { indent: 4 });
    } else if (line.match(/^\d+\. /)) {
      addText(line, { indent: 4 });
    } else if (line === '---') {
      addHRule();
    } else if (line === '') {
      y += 2;
    } else {
      // Strip inline bold (**text**) for plain rendering
      const plain = line.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1');
      addText(plain);
    }
  }

  // Footer on all pages
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${p} of ${totalPages} · Generated by Lesson Plan Analyzer`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  doc.save(filename);
}
